services:
  ai-recommender:
    container_name: ai-recommender
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
    command: ./entrypoint.sh
    networks:
      - llt-net

networks:
  llt-net:
    external: true
    name: llt-net
